version: '3.8'

services:
  platform:
    container_name: platform
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
      - /app/node_modules
    user: root
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
